name: exposingARTS
favicon: null
layout_spectrum: 0.6205730428919196
typography_spectrum: 0.5656720148399472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#758897'
    - '#be4c6d'
    - '#ff91a9'
    - '#56d7bb'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 1
purpose: []
