name: exposingARTS
favicon: null
layout_spectrum: 0.40572
typography_spectrum: 0.90655
title: exposingARTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090806'
    - '#c31900'
    - '#0046c8'
    - '#b3b3a9'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 1
purpose: []
